[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION  = "11.4.2"
  NPM_FLAGS    = "--include=dev"

[[plugins]]
  package = "@netlify/plugin-prerender"
  [plugins.inputs]
    crawl = true

[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    formats = ["webp", "avif"]
