backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow   # => workflow avec branches + PR
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
i18n:
  structure: multiple_files
  locales: [en, fr, es]
  default_locale: en
collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Article"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/{{locale}}"   # crée en.md, fr.md, es.md dans chaque sous-dossier
    extension: "md"
    i18n: true
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: true }
      - { label: "Description", name: "description", widget: "text", required: false, i18n: true }
      - { label: "Category", name: "category", widget: "string", required: false, i18n: true }
      - { label: "Cover Image", name: "image", widget: "image", required: false, i18n: duplicate }
      - { label: "Tags", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
