backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow   # => workflow avec branches + PR
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
i18n:
  structure: multiple_files
  locales: [en, fr, es]
  default_locale: en
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "md"
    format: "frontmatter"
    i18n: true
    summary: "{{slug}} {{title}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Author", name: "author", widget: "string", required: false, i18n: duplicate }
      - { label: "Category", name: "category", widget: "string", required: false, i18n: true }
      - { label: "Cover Image", name: "image", widget: "image", required: false, i18n: duplicate }
    - { label: "Video", name: "video", widget: "string", required: false, i18n: duplicate }
    - { label: "Description", name: "description", widget: "text", required: false, i18n: true }
    - { label: "Body",  name: "body",  widget: "markdown", i18n: true }
  - name: "faq"
    label: "FAQ"
    folder: "src/content/faq"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "md"
    format: "frontmatter"
    i18n: true
    summary: "{{slug}} {{question}}"
    fields:
      - { label: "Question", name: "question", widget: "string", i18n: true }
      - { label: "Answer", name: "body", widget: "markdown", i18n: true }
