backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/aimeecotetherapy
  branch: main
  auth: { token: true }
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
i18n:
  structure: multiple_files
  locales: [en, fr, es]
  default_locale: en
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Author", name: "author", widget: "string", i18n: true }
      - { label: "Category", name: "category", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: duplicate }
      - { label: "Video", name: "video", widget: "string", required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
